<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\LicenciamentoSoftware.Application\LicenciamentoSoftware.Application.csproj" />
    <ProjectReference Include="..\LicenciamentoSoftware.Domain\LicenciamentoSoftware.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.35" />
    <PackageReference Include="dbup-postgresql" Version="5.0.37" />
    <PackageReference Include="Npgsql" Version="9.0.3" />
  </ItemGroup>

  <!-- Embarca os scripts SQL de migration no assembly para uso pelo DbUp -->
  <ItemGroup>
    <EmbeddedResource Include="Persistence\Migrations\*.sql" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
