<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <!-- Suprime aviso de TreatWarningsAsErrors para projetos web com Razor -->
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="10.0.10" />
    <PackageReference Include="QRCoder" Version="1.6.0" />
    <PackageReference Include="Yarp.ReverseProxy" Version="2.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LicenciamentoSoftware.Client\LicenciamentoSoftware.Client.csproj" />
    <ProjectReference Include="..\LicenciamentoSoftware.Web\LicenciamentoSoftware.Web.csproj" />
  </ItemGroup>

</Project>
