// <auto-generated />
using System;
using LicenciamentoSoftware.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LicenciamentoSoftware.Infrastructure.Migrations
{
    [DbContext(typeof(LicenciamentoDbContext))]
    [Migration("20260727183033_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LicenciamentoSoftware.Domain.Entities.Aplicacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descricao")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("IdCliente")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdTipoLicenca")
                        .HasColumnType("uuid");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdTipoLicenca");

                    b.ToTable("Aplicacao", (string)null);
                });

            modelBuilder.Entity("LicenciamentoSoftware.Domain.Entities.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("NumeroInscricao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<int>("TipoInscricao")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Cliente", (string)null);
                });

            modelBuilder.Entity("LicenciamentoSoftware.Domain.Entities.ClienteFinal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("IdCliente")
                        .HasColumnType("uuid");

                    b.Property<string>("NumeroInscricao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<int>("TipoInscricao")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdCliente");

                    b.ToTable("ClienteFinal", (string)null);
                });

            modelBuilder.Entity("LicenciamentoSoftware.Domain.Entities.Licenca", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdAplicativo")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdCliente")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdClienteFinal")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IdAplicativo");

                    b.HasIndex("IdClienteFinal");

                    b.HasIndex("IdCliente", "IdClienteFinal", "IdAplicativo")
                        .IsUnique()
                        .HasDatabaseName("uq_licenca_combinacao_ativa")
                        .HasFilter("\"Ativo\" = true");

                    b.ToTable("Licenca", (string)null);
                });

            modelBuilder.Entity("LicenciamentoSoftware.Domain.Entities.LicencaInstalacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("LicencaId")
                        .HasColumnType("uuid");

                    b.Property<int>("QuantidadeMaxima")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LicencaId")
                        .IsUnique();

                    b.ToTable("LicencaInstalacao", (string)null);
                });

            modelBuilder.Entity("LicenciamentoSoftware.Domain.Entities.LicencaInstalacaoRegistrada", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdentificadorMaquina")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("LicencaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LicencaId", "IdentificadorMaquina")
                        .IsUnique()
                        .HasDatabaseName("uq_licencainstalacao_maquina_ativa")
                        .HasFilter("\"Ativo\" = true");

                    b.ToTable("LicencaInstalacaoRegistrada", (string)null);
                });

            modelBuilder.Entity("LicenciamentoSoftware.Domain.Entities.LicencaPeriodo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LicencaId")
                        .HasColumnType("uuid");

                    b.Property<bool>("RenovacaoAutomatica")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("LicencaId")
                        .IsUnique();

                    b.ToTable("LicencaPeriodo", (string)null);
                });

            modelBuilder.Entity("LicenciamentoSoftware.Domain.Entities.LicencaSessao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("DataLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataUltimaAtividade")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdentificadorUsuario")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("LicencaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LicencaId", "Ativo");

                    b.HasIndex("LicencaId", "IdentificadorUsuario", "Ativo");

                    b.ToTable("LicencaSessao", (string)null);
                });

            modelBuilder.Entity("LicenciamentoSoftware.Domain.Entities.LicencaUsuarios", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("LicencaId")
                        .HasColumnType("uuid");

                    b.Property<int>("MaxSessoesPorUsuario")
                        .HasColumnType("integer");

                    b.Property<int>("QuantidadeMaxima")
                        .HasColumnType("integer");

                    b.Property<int>("TempoLimiteSessaoHoras")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LicencaId")
                        .IsUnique();

                    b.ToTable("LicencaUsuarios", (string)null);
                });

            modelBuilder.Entity("LicenciamentoSoftware.Domain.Entities.LogOperacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CamposAlterados")
                        .HasColumnType("text");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Entidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("IdRegistro")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IdUsuario")
                        .HasColumnType("uuid");

                    b.Property<char>("Operacao")
                        .HasColumnType("character(1)");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("Entidade", "IdRegistro");

                    b.ToTable("LogOperacao", (string)null);
                });

            modelBuilder.Entity("LicenciamentoSoftware.Domain.Entities.TipoLicenca", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("TipoLicenca", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Descricao = "Permanente"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Descricao = "Por Período"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Descricao = "Por Usuários"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Descricao = "Por Instalação"
                        });
                });

            modelBuilder.Entity("LicenciamentoSoftware.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<Guid>("IdCliente")
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("IdCliente");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("LicenciamentoSoftware.Domain.Entities.Aplicacao", b =>
                {
                    b.HasOne("LicenciamentoSoftware.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Aplicacoes")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LicenciamentoSoftware.Domain.Entities.TipoLicenca", "TipoLicenca")
                        .WithMany()
                        .HasForeignKey("IdTipoLicenca")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("TipoLicenca");
                });

            modelBuilder.Entity("LicenciamentoSoftware.Domain.Entities.ClienteFinal", b =>
                {
                    b.HasOne("LicenciamentoSoftware.Domain.Entities.Cliente", "Cliente")
                        .WithMany("ClientesFinais")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("LicenciamentoSoftware.Domain.Entities.Licenca", b =>
                {
                    b.HasOne("LicenciamentoSoftware.Domain.Entities.Aplicacao", "Aplicativo")
                        .WithMany("Licencas")
                        .HasForeignKey("IdAplicativo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LicenciamentoSoftware.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Licencas")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LicenciamentoSoftware.Domain.Entities.ClienteFinal", "ClienteFinal")
                        .WithMany("Licencas")
                        .HasForeignKey("IdClienteFinal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aplicativo");

                    b.Navigation("Cliente");

                    b.Navigation("ClienteFinal");
                });

            modelBuilder.Entity("LicenciamentoSoftware.Domain.Entities.LicencaInstalacao", b =>
                {
                    b.HasOne("LicenciamentoSoftware.Domain.Entities.Licenca", "Licenca")
                        .WithOne("Instalacao")
                        .HasForeignKey("LicenciamentoSoftware.Domain.Entities.LicencaInstalacao", "LicencaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Licenca");
                });

            modelBuilder.Entity("LicenciamentoSoftware.Domain.Entities.LicencaInstalacaoRegistrada", b =>
                {
                    b.HasOne("LicenciamentoSoftware.Domain.Entities.Licenca", "Licenca")
                        .WithMany("InstalacoesRegistradas")
                        .HasForeignKey("LicencaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Licenca");
                });

            modelBuilder.Entity("LicenciamentoSoftware.Domain.Entities.LicencaPeriodo", b =>
                {
                    b.HasOne("LicenciamentoSoftware.Domain.Entities.Licenca", "Licenca")
                        .WithOne("Periodo")
                        .HasForeignKey("LicenciamentoSoftware.Domain.Entities.LicencaPeriodo", "LicencaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Licenca");
                });

            modelBuilder.Entity("LicenciamentoSoftware.Domain.Entities.LicencaSessao", b =>
                {
                    b.HasOne("LicenciamentoSoftware.Domain.Entities.Licenca", "Licenca")
                        .WithMany("Sessoes")
                        .HasForeignKey("LicencaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Licenca");
                });

            modelBuilder.Entity("LicenciamentoSoftware.Domain.Entities.LicencaUsuarios", b =>
                {
                    b.HasOne("LicenciamentoSoftware.Domain.Entities.Licenca", "Licenca")
                        .WithOne("Usuarios")
                        .HasForeignKey("LicenciamentoSoftware.Domain.Entities.LicencaUsuarios", "LicencaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Licenca");
                });

            modelBuilder.Entity("LicenciamentoSoftware.Domain.Entities.LogOperacao", b =>
                {
                    b.HasOne("LicenciamentoSoftware.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("LicenciamentoSoftware.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("LicenciamentoSoftware.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("LicenciamentoSoftware.Domain.Entities.Aplicacao", b =>
                {
                    b.Navigation("Licencas");
                });

            modelBuilder.Entity("LicenciamentoSoftware.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Aplicacoes");

                    b.Navigation("ClientesFinais");

                    b.Navigation("Licencas");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("LicenciamentoSoftware.Domain.Entities.ClienteFinal", b =>
                {
                    b.Navigation("Licencas");
                });

            modelBuilder.Entity("LicenciamentoSoftware.Domain.Entities.Licenca", b =>
                {
                    b.Navigation("Instalacao");

                    b.Navigation("InstalacoesRegistradas");

                    b.Navigation("Periodo");

                    b.Navigation("Sessoes");

                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
