name: Publicar Documentação (GitHub Pages)

on:
  push:
    branches:
      - master
    paths:
      - "docs/**"
      - "mkdocs.yml"
      - ".github/workflows/docs.yml"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy-docs:
    name: Build e Deploy MkDocs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0   # necessário para git-revision-date-localized

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Instalar MkDocs e plugins
        run: |
          pip install \
            mkdocs==1.6.1 \
            mkdocs-material==9.5.34 \
            pymdown-extensions==10.9

      - name: Build e Deploy para gh-pages
        run: mkdocs gh-deploy --force --clean --verbose
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
